{% set name = "executing" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a232a732603eba24ff863632f2389b73072baadc185aa9e290a4792ae9f700b8

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/alexmojaki/executing
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Get the currently executing AST node of a frame, and other information
  doc_url: https://github.com/alexmojaki/executing
  dev_url: https://github.com/alexmojaki/executing

extra:
  recipe-maintainers:
    - alexmojaki
