{% set name = "executing" %}
{% set version = "0.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07b71adef0399e8579fa0165db5e5f8e9dd961fa66572664de95c838879768eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python

test:
  imports:
    - executing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/executing
  summary: Get the currently executing AST node of a frame, and other information
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/alexmojaki/executing

extra:
  recipe-maintainers:
    - alexmojaki
    - anthchirp
