{% set name = "executing" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da16e4b44d4d209ea9cfc63d68f3d105a38bb53ecf77d79ab5115867759b388f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/alexmojaki/executing
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Get the currently executing AST node of a frame, and other information
  doc_url: https://github.com/alexmojaki/executing
  dev_url: https://github.com/alexmojaki/executing

extra:
  recipe-maintainers:
    - alexmojaki
